title: Page par default

fields:
  contenu:
    label: Contenu
    type: blocks
    fieldsets:
      - videoautoplay
      - listeliens
      - cta
      - video
      - image
      - iframe
      - contenu
      - toggle
