title: Page par default


columns:
  - width: 1/3
    sections:
      subpages:
        type: pages
        headline: Sous-pages
        template: default
      meta_tags:
        type: fields
        fields:
          tags:
            label: Tags
            type: pages
            query: site.find('tags').children
            multiple: true
            layout: list

  - width: 2/3
    fields:
      contenu:
        label: Contenu
        type: blocks
        fieldsets:
          - videoautoplay
          - listeliens
          - cta
          - video
          - image
          - iframe
          - contenu
          - toggle


